### PR TITLE
Update `count` function to incorporate `limit`.

### PR DESCRIPTION
**Pull request by Dinesh-Quollio**
Updated `count` function to incorporate `limit`.

### CODE REVIEW

**Review by TakumiHaruta — CHANGES_REQUESTED** [review]
@Dinesh-Quollio 

Thanks! I'm just wondering is it possible to set the limit like that?
Should be better if we can still use `Count(context.Background())` since `CountWithLimt()` looks duplicated

```
err = db.
		GSI("gsi-name", "room", Equal("current")).
		Filter("physical_name", KeyBeginsWith(prefix)).
		AndFilter("logical_name", KeyBeginsWith(prefix)).
		Limit(100).
		Count(context.Background())
```

**Comment by Dinesh-Quollio** [comment]
@TakumiHaruta Sure.
Existing `Count()` function doesn't support `Limit`. I will modify it.

**Comment by Dinesh-Quollio** [comment]
@TakumiHaruta Updated `count` function to incorporate `limit`.

**Review by TakumiHaruta — COMMENTED** [review]
@Dinesh-Quollio 
Thanks! Looks good but have you tested this function to DynamoDB?
Would like to confirm if this API meets our expectation;

- The number or records on the GSI with limit(100)
    - 0 ~ 100: Get exact number
    - 101 ~ : Get 100

**Comment by Dinesh-Quollio** [comment]
@TakumiHaruta Yes, I have tested it with local DynamoDB, test cases are working as exception.

**Review by TakumiHaruta — APPROVED** [review]

**Pull request merged**
